---
- name: ACI Playbook 
  hosts: apic
  connection: local
  gather_facts: no
  vars_files:
    - vars/topology.yml
    - vars/tenant-info.yml
  roles:
    - access-build
    - tenant-build
    - net-migration
    - best-practices-check