---
- name: ACI Playbook
  hosts: apic
  connection: local
  gather_facts: no
  vars_files:
    - vars/topology.yml
    - vars/tenant-info.yml
  roles:
    #- access_build
    #- tenant_build
    - net_migration
    #- best_practices_check
    #- epg_to_port